// Auto generated by using a json to typescript converter.
export type RepoList = Repo[];

export interface Repo {
  _id: string;
  id: string;
  author: string;
  gated: any;
  lastModified: string;
  likes: number;
  trendingScore: number;
  private: boolean;
  sha: string;
  downloads: number;
  tags: string[];
  pipeline_tag?: string;
  library_name?: string;
  createdAt: string;
  modelId: string;
  siblings: Sibling[];
}

export interface Sibling {
  rfilename: string;
}
